export const ADD_LOADING = 'ADD_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

export const LOAD_ALL_GISTS_SUCCESS = 'LOAD_ALL_GISTS_SUCCESS';
export const LOAD_ALL_GISTS_FAILURE = 'LOAD_ALL_GISTS_FAILURE';

export const LOAD_GIST_SUCCESS = 'LOAD_GIST_SUCCESS';
export const LOAD_GIST_FAILURE = 'LOAD_GIST_FAILURE';
